### ISSUE TITLE
mjs extension

### ISSUE THREAD

**Issue by ottoo** [ABWalters/react-api-hooks#1]
The microbundler node target should be set to web. Cannot use this library with CRA, because it doesn't support mjs yet and Webpack picks up the index.mjs file and I get a compilation error ```Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)```

**Comment by ABWalters** [comment]
Thanks for reporting the issue.

I have removed the 'module' field in the package.json file.

`v0.2.1` of the package works correctly when I tested it with CRA.
